### ISSUE TITLE
A couple of typos

### ISSUE THREAD

**Issue by stuartpullinger** [trescenzi/hello-wasm#1]
Hi,

Thanks for the guide. I spotted a couple of typos:

- somewhere you use the word "contagious" where you mean "contiguous"
- this: "Additionally there are also tables(expandable byte arrays), reference types(currently only implemented by Firefox), and value types(can be a reference or a number) however we won't be going into those in this example."
  - should be something like: "Additionally there are also tables (indexable "arrays" of function pointers), memories(expandable byte arrays), ..."

**Comment by trescenzi** [comment]
Thank you! I wrote the readme in 45min over lunch. Love seeing that some people are actually reading it even 😄. I'll update it.
